version: 2.1
orbs:
  node: circleci/node@4.5.0
jobs:
  build:
    executor:
      name: node/default
      tag: '14.17.1'
    steps:
      - checkout
      - node/install-yarn
      - run: npm run test
        
  
