version: 2.1
orbs:
  node: circleci/node@4.5.0
jobs:
  build:
    executor:
      name: node/default
      tag: '14.17.1'
    steps:
      - checkout
      - node/with-cache
        steps:
          - run: npm install
      - run: npm run test
        
  
